#pragma once
/* ======================= Material ======================= */

#define WALL 0
#define ROAD 1
#define LAVA 2
#define WALL_SHINE 73

/* ======================= Entity ======================= */

#define GIRAFFE 1
#define BOX 2
#define	UP_STAIR 3
#define DOOR 4
#define SILVER_DOOR 5
#define GOLD_DOOR 6
#define GRAPE 7
#define GOLD_KEY 8
#define SILVER_KEY 9
#define KEY 10
#define SUSHI 11
#define GREEN_SLIME 12
#define DOWN_STAIR 13
#define RED_SLIME 14 
#define BAT 15
#define ZOMBIE 16
#define SKELETON_C 17
#define SHOPKEEPER 18
#define SHOP1 19
#define SHOP2 20
#define SHOP3 21
#define RUBY 22
#define SAPPHIRE 23
#define RED_POTION 24
#define BLUE_POTION 25
#define BIGBAT 26
#define BIGSLIME 27
#define DARK_KNIGHT 28
#define ELDER 29
#define EMERALD 30
#define FAIRY 31
#define GATE_KEEPER_A 32
#define GATE_KEEPER_B 33
#define GATE_KEEPER_C 34
#define GREAT_MAGIC_MASTER 35
#define IRON_KNIGHT_A 36
#define IRON_KNIGHT_B 37
#define KNIGHT 38
#define MAGACIAN_A 39
#define MAGACIAN_B 40
#define MAGIC_SERGEANT_A 41
#define MAGIC_SERGEANT_B 42
#define MAGIC_SERGEANT_C 43
#define MAGIC_SERGEANT_D 44
#define PRIEST_A 45
#define PRIEST_B 46
#define PRIEST_C 47
#define SKELETON_A 48
#define SKELETON_B 49
#define SLIME_LORD 50
#define SLIME_MEN 51
#define SOUL_SKELETON 52
#define SOUL_SKELETON_KNIGHT 53
#define STONE_MONSTER_A 54
#define STONE_MONSTER_B 55
#define SWORD_MEN 56
#define THIEF 57
#define VAMPIRE 58
#define VAMPIRE_BAT 59
#define ZOMBIE_KNIGHT 60
#define FIRE_DRINK 61
#define ANTI_POTION 62
#define JUMP_WING 63
#define SHOP_2_1 64
#define SHOP_2_2 65
#define SHOP_2_3 66
#define IRON_FENCE 67
#define GEM_DIGGER 68
#define COIN_200 69
#define MAGIC_KEY 70
#define SHIELD_C 71
#define GEM_DOOR 72
#define LIGHT_SHIELD 74
#define SWORD_B 75
#define GEM_HOE 76
#define WALL_SPECIAL 77
#define PRINCESS 78
#define SWORD_A 79
#define SWORD_C 80
#define SWORD_D 81
#define SHIELD_D 82

/* ======================= End ======================= */
